# Generated by Django 2.1.7 on 2020-08-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
