# Generated by Django 2.1.7 on 2020-08-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='confirmation',
            new_name='email_confirmed',
        ),
    ]
