# Generated by Django 2.1.7 on 2020-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200805_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'USER')], default=2, max_length=1),
        ),
    ]
