# Generated by Django 2.1.7 on 2020-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default=2, max_length=1),
        ),
    ]
