# Generated by Django 2.1.7 on 2020-08-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200811_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workoutLength', models.TimeField()),
                ('workoutType', models.CharField(choices=[('CARDIO', 'Cardio'), ('HIIT', 'HIIT'), ('WEIGHTS', 'Weights')], max_length=100)),
            ],
        ),
    ]
