# Generated by Django 2.1.7 on 2020-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_checkin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
