# Generated by Django 2.1.7 on 2020-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
