# Generated by Django 2.1.7 on 2020-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200818_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='workoutType',
            field=models.CharField(choices=[('WEIGHTS', 'Weights'), ('CARDIO', 'Cardio'), ('SWIMMING', 'Swimming'), ('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('SPORTS', 'Sports'), ('SOCCER', 'Soccer'), ('VOLLEYBALL', 'Volleyball'), ('GOLF', 'Golf'), ('HUNTING', 'Hunting'), ('HIKING', 'Hiking'), ('HIIT', 'HIIT'), ('YOGA', 'Yoga'), ('CROSSFIT', 'Crossfit')], max_length=100),
        ),
    ]
