# Generated by Django 2.1.7 on 2020-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_challengesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='repeat',
            field=models.CharField(choices=[(1, 'Never'), (2, 'Weekly'), (3, 'Bi-Weekly'), (4, 'Bi-Monthly'), (5, 'Monthly')], default='Never', max_length=10),
        ),
    ]
