# Generated by Django 2.1.7 on 2020-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200831_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='repeat',
            field=models.CharField(choices=[('Never', 'Never'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Bi-Monthly', 'Bi-Monthly'), ('Monthly', 'Monthly')], default='Never', max_length=10),
        ),
    ]
