# Generated by Django 2.1.7 on 2020-09-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200831_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='response',
            field=models.IntegerField(choices=[(1, 'Time'), (2, 'Amount')], default=2),
        ),
    ]
