# Generated by Django 2.1.7 on 2020-09-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200831_1323'),
        ('api', '0013_auto_20200904_1037'),
    ]

    operations = [
    ]
