# Generated by Django 2.1.7 on 2020-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_challenge_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='response',
            field=models.CharField(choices=[('Time', 'Time'), ('Amount', 'Amount')], default='Amount', max_length=10),
        ),
    ]
