# Generated by Django 2.1.7 on 2020-09-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200901_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge', to='api.Challenge'),
        ),
    ]
