# Generated by Django 2.1.7 on 2020-09-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20200904_1320'),
        ('api', '0021_auto_20200904_1009'),
    ]

    operations = [
    ]
