# Generated by Django 2.1.7 on 2020-10-07 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_merge_20200929_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='api.Challenge'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='workoutType',
            field=models.CharField(choices=[('WEIGHTS', 'Weights'), ('CARDIO', 'Cardio'), ('SWIMMING', 'Swimming'), ('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('SPORTS', 'Sports'), ('SOCCER', 'Soccer'), ('VOLLEYBALL', 'Volleyball'), ('GOLF', 'Golf'), ('HUNTING', 'Hunting'), ('HIKING', 'Hiking'), ('HIIT', 'HIIT'), ('CALISTHENICS', 'Calisthenics'), ('YOGA', 'Yoga'), ('CROSSFIT', 'Crossfit')], max_length=100),
        ),
    ]
