# Generated by Django 2.1.7 on 2020-12-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201012_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA-LARGE', 'Extra-Large')], default='LARGE', max_length=5),
        ),
    ]
