# Generated by Django 2.1.7 on 2020-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_profile_shirt_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA-LARGE', 'Extra-Large')], default='LARGE', max_length=20),
        ),
    ]
