# Generated by Django 2.1.7 on 2020-12-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201222_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.BooleanField(default='False'),
        ),
    ]
