# Generated by Django 2.1.7 on 2020-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_profile_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registrationSubmission',
            field=models.ManyToManyField(to='api.Upload'),
        ),
    ]
