# Generated by Django 2.1.7 on 2021-01-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_profile_registrationsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registrationSubmission',
            field=models.ManyToManyField(blank=True, null=True, to='api.Upload'),
        ),
    ]
