# Generated by Django 2.1.7 on 2020-08-24 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('thumb_nail', models.URLField(blank=True, null=True)),
                ('security', models.SmallIntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1)),
                ('createdBy', models.ForeignKey(on_delete=None, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
                ('lastUpdatedBy', models.ForeignKey(on_delete=None, related_name='lastUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(to='api.Item'),
        ),
    ]
