# Generated by Django 2.1.7 on 2020-08-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200824_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Hidden')], default=1),
        ),
    ]
