# Generated by Django 2.1.7 on 2020-08-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200813_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionentry',
            name='signature',
            field=models.URLField(blank=True, null=True),
        ),
    ]
