# Generated by Django 2.1.7 on 2020-08-13 20:32

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AlterField(
            model_name='petitionentry',
            name='signature',
            field=models.FileField(blank=True, null=True, storage=backend.storage_backends.SignatureStorage(), upload_to=''),
        ),
    ]
