# Generated by Django 2.1.7 on 2020-08-13 20:34

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200813_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=backend.storage_backends.SignatureStorage(), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='petitionentry',
            name='signature',
            field=models.URLField(blank=True, null=True),
        ),
    ]
