# Generated by Django 2.1.7 on 2020-08-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitionentry',
            name='petition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Petition'),
            preserve_default=False,
        ),
    ]
