# Generated by Django 2.1.7 on 2020-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_petitionentry_petition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitionentry',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
