# Generated by Django 2.1.7 on 2020-09-17 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20200911_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeSurveyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_representative', models.BooleanField()),
                ('security_representative', models.BooleanField()),
                ('health_representative', models.BooleanField()),
                ('law_representative', models.BooleanField()),
                ('culture_representative', models.BooleanField()),
                ('education_representative', models.BooleanField()),
                ('sports_representative', models.BooleanField()),
                ('treasury_representative', models.BooleanField()),
                ('social_representative', models.BooleanField()),
                ('info_tech_representative', models.BooleanField()),
                ('misc_representative', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
