# Generated by Django 2.1.7 on 2020-09-22 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20200916_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='lastUpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='lastUpdatedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
