# Generated by Django 2.1.7 on 2020-09-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_credencialsurveyentry_votingforammonsurveyentry'),
        ('api', '0020_thumbnail'),
    ]

    operations = [
    ]
