# Generated by Django 2.1.7 on 2020-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_merge_20201006_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('symbol', models.CharField(max_length=4)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
