# Generated by Django 2.1.7 on 2020-11-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20201102_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspage',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.BusinessPagePhoto'),
        ),
        migrations.AlterField(
            model_name='businesspage',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, to='api.BusinessPagePost'),
        ),
        migrations.AlterField(
            model_name='businesspagepost',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='api.BusinessPagePhoto'),
        ),
    ]
