# Generated by Django 2.1.7 on 2020-11-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20201109_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspagepost',
            options={},
        ),
    ]
