# Generated by Django 2.1.7 on 2020-11-09 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20201109_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspage',
            name='posts',
        ),
        migrations.AddField(
            model_name='businesspagepost',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.BusinessPage'),
            preserve_default=False,
        ),
    ]
