# Generated by Django 2.1.7 on 2020-11-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_directory_businesspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspage',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pending'), (2, 'Live')], default=1),
        ),
    ]
