# Generated by Django 2.1.7 on 2020-11-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_businesspage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Live')], default=1),
        ),
    ]
