# Generated by Django 2.1.7 on 2020-11-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201111_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rate',
            new_name='buy',
        ),
        migrations.AddField(
            model_name='currency',
            name='sell',
            field=models.DecimalField(decimal_places=3, default=12.0, max_digits=100),
            preserve_default=False,
        ),
    ]
