# Generated by Django 2.1.7 on 2021-02-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_stripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptionActive',
            field=models.BooleanField(default=False),
        ),
    ]
