# Generated by Django 2.1.7 on 2021-03-22 14:25

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=backend.storage_backends.BusinessPagePhotoStorage(), upload_to='')),
            ],
        ),
    ]
