# Generated by Django 2.1.7 on 2021-04-29 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffleentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='raffleentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='RaffleEntry',
        ),
        migrations.DeleteModel(
            name='RaffleItem',
        ),
    ]
