# Generated by Django 2.1.7 on 2021-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Antiques & collectibles'), (2, 'Arts & Crafts'), (3, 'Auto Parts & Accessories'), (4, 'Baby Products'), (5, 'Bags & Luggage'), (6, 'Books, Movies & Music'), (7, 'Cell PHone & Accessories'), (8, 'Clothing, Shoes & Accessories'), (9, 'Electronics'), (10, 'Furniture'), (11, 'Health & Beauty'), (12, 'Home & Kitchen'), (13, 'Jewelry & Watches'), (14, 'Musical Instruments'), (15, 'Office Supplies'), (16, 'Patio & Garden'), (17, 'Pet Supplies'), (18, 'Sporting Goods'), (19, 'Tools & Home Improvement'), (20, 'Toys & Games'), (21, 'Video Games & Consoles'), (22, 'Miscellaneous')]),
        ),
    ]
