# Generated by Django 2.1.7 on 2021-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_raffleentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffleentry',
            name='stripeRaffleEntryId',
        ),
        migrations.AddField(
            model_name='raffleentry',
            name='payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raffleentry',
            name='stripePaymentIntent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='raffleentry',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
