# Generated by Django 2.1.7 on 2021-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210322_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Used - Like New'), (3, 'Used - Good'), (4, 'Used - Fair')], default=1),
            preserve_default=False,
        ),
    ]
