# Generated by Django 2.1.7 on 2021-05-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0048_auto_20210429_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='YOI_Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=255)),
                ('reasonOne', models.CharField(max_length=1500)),
                ('reasonTwo', models.CharField(max_length=1500)),
                ('giftOne', models.CharField(max_length=1500)),
                ('giftTwo', models.CharField(max_length=1500)),
                ('giftThree', models.CharField(max_length=1500)),
                ('suggestionOne', models.CharField(max_length=1500)),
                ('suggestionTwo', models.CharField(max_length=1500)),
                ('suggestionThree', models.CharField(max_length=1500)),
                ('classOne', models.CharField(max_length=1500)),
                ('classTwo', models.CharField(max_length=1500)),
                ('signature', models.CharField(max_length=1500)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
