# Generated by Django 2.1.7 on 2021-05-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_yoi_assistant'),
        ('api', '0048_auto_20210419_1315'),
    ]

    operations = [
    ]
