# Generated by Django 2.1.7 on 2021-03-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_listing_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pick Up')], default=1),
            preserve_default=False,
        ),
    ]
