# Generated by Django 2.1.7 on 2021-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20210323_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='email',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='email',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
