# Generated by Django 2.1.7 on 2021-05-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_yoi_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoi_registration',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Parent'),
            preserve_default=False,
        ),
    ]
