# Generated by Django 2.1.7 on 2021-04-02 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210323_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelisting',
            old_name='condition',
            new_name='exterior_condition',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='vehiclelisting',
            name='email',
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='callEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='emailEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='interior_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Excellent'), (2, 'Very Good'), (3, 'Good'), (4, 'Fair'), (5, 'Poor')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='textEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='trim',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclelisting',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='model',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
