# Generated by Django 2.1.7 on 2021-05-25 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_yoi_registration_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoi_registration',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
