# Generated by Django 2.1.7 on 2021-04-02 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20210402_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='email',
        ),
        migrations.AddField(
            model_name='listing',
            name='callEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='emailEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='textEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='exterior_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Excellent'), (3, 'Very Good'), (4, 'Good'), (5, 'Fair'), (6, 'Poor')]),
        ),
        migrations.AlterField(
            model_name='vehiclelisting',
            name='interior_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Excellent'), (3, 'Very Good'), (4, 'Good'), (5, 'Fair'), (6, 'Poor')]),
        ),
    ]
