# Generated by Django 2.1.7 on 2021-05-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20210525_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='child',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RenameField(
            model_name='yoi_registration',
            old_name='child_first_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='allergies',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='size',
            field=models.CharField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=2, max_length=25),
        ),
        migrations.AlterField(
            model_name='yoi_registration',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
