# Generated by Django 2.1.7 on 2021-05-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20210525_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoi_registration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='yoi_registration',
            name='shirt_size',
        ),
    ]
