# Generated by Django 2.1.7 on 2021-04-05 09:48

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20210402_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='file',
            field=models.FileField(storage=backend.storage_backends.ListingImageStorage(), upload_to=''),
        ),
    ]
