# Generated by Django 2.1.7 on 2021-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_listing_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelisting',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
