# Generated by Django 2.1.7 on 2021-05-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20210525_1143'),
        ('api', '0062_remove_listing_draft'),
    ]

    operations = [
    ]
