# Generated by Django 2.1.7 on 2021-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_merge_20210528_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoi_registration',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unknown')], default=2, max_length=25),
        ),
    ]
