# Generated by Django 2.1.7 on 2021-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_yoi_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoi_registration',
            name='spanish_shirt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yoi_registration',
            name='translation_assistance',
            field=models.BooleanField(default=False),
        ),
    ]
