# Generated by Django 2.1.7 on 2021-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20210604_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoi_registration',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unknown')], default=2),
        ),
        migrations.AlterField(
            model_name='yoi_registration',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=2),
        ),
    ]
