# Generated by Django 2.1.7 on 2021-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20210609_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoi_registration',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, '12/14'), (6, '14/16'), (7, 'Other')], default=2),
        ),
    ]
