# Generated by Django 2.1.7 on 2021-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20210616_1108'),
        ('api', '0067_auto_20210608_1403'),
    ]

    operations = [
    ]
