# Generated by Django 2.1.7 on 2021-06-22 09:46

import backend.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_merge_20210621_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=backend.storage_backends.ProfileImageStorage(), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ProfileImage'),
        ),
    ]
