# Generated by Django 2.1.7 on 2021-06-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_merge_20210621_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raffleentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='RaffleEntry',
        ),
    ]
