# Generated by Django 2.2.24 on 2021-08-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_classifiedfavorite'),
        ('api', '0070_raffleentry'),
    ]

    operations = [
    ]
