# Generated by Django 2.2.24 on 2021-09-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_merge_20210826_1618'),
        ('api', '0070_auto_20210622_1050'),
    ]

    operations = [
    ]
